# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PackSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PackSizeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solawi.Food')),
                ('packsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solawi.PackSize')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='The persons first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='The persons last name')),
                ('mail', models.EmailField(max_length=254, verbose_name='The persons E-Mail address')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solawi.User')),
            ],
            bases=('solawi.user',),
        ),
        migrations.AddField(
            model_name='food',
            name='packsizes',
            field=models.ManyToManyField(through='solawi.PackSizeRelation', to='solawi.PackSize'),
        ),
        migrations.CreateModel(
            name='Depotbesteller',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solawi.Member')),
            ],
            bases=('solawi.member',),
        ),
        migrations.AddField(
            model_name='member',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solawi.Depot'),
        ),
    ]
