# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 16:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import solawi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('solawi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='price',
            field=models.FloatField(default=0, help_text='The price of this Portion.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.TextField(blank=True, default=0, help_text='Containing the JSON array of this users gained potentials', null=True, validators=[solawi.validators.portion_account_validate]),
        ),
        migrations.AlterField(
            model_name='user',
            name='assets',
            field=models.IntegerField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
