# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solawi', '0002_auto_20170315_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('contents', models.ManyToManyField(to='solawi.Portion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order basket',
                'verbose_name_plural': 'order baskets',
            },
        ),
        migrations.AlterUniqueTogether(
            name='orderbasket',
            unique_together=set([('week', 'user')]),
        ),
    ]
