# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solawi', '0003_auto_20170316_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasket',
            name='edited_weekly_basket',
            field=models.BooleanField(default=False, verbose_name='Has edited the weekly basket for this week'),
        ),
    ]
